export interface Leader {
  id: string;
  name: string;
  handle: string;
  campus: string;
  winRate: number;
  maxDrawdown: number;
  skinInGame: number;
  totalTrades: number;
  followers: number;
  followersFormatted: string;
  badge?: string;
}

export interface SyndicateItem {
  id: string;
  title: string;
  catalyst: string;
  assetSymbol: string;
  ticker: string;
  assetName: string;
  direction: "LONG" | "SHORT";
  leverage: number;
  entryPrice: number;
  stopLossPrice: number;
  targetPrice: number;
  targetReturnPct: number;
  returnTarget: number;
  circuitBreakerPct: number;
  stopLoss: number;
  minPledge: number;
  poolCap: number;
  currentPooled: number;
  pooledAmount: number;
  participants: number;
  status: string;
  category: "Tech/AI" | "Crypto" | "Earnings" | "High-Beta" | "Consumer Tech";
  leader: Leader;
  lead: Leader;
  positions?: any[];
  pledges?: any[];
}

export const DEFAULT_MOCK_SYNDICATES: SyndicateItem[] = [
  {
    id: "syn_nvda_q3",
    title: "NVDA Q3 Blackwell Data Center Surge",
    catalyst: "Record ultra-hyperscaler GPU capex + Blackwell B200 delivery acceleration. Historical earnings move ±9.4%.",
    assetSymbol: "NVDA",
    ticker: "NVDA",
    assetName: "NVIDIA Corp",
    direction: "LONG",
    leverage: 10,
    entryPrice: 128.50,
    stopLossPrice: 127.21,
    targetPrice: 151.63,
    targetReturnPct: 35,
    returnTarget: 35,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 250000,
    currentPooled: 185000,
    pooledAmount: 185000,
    participants: 1240,
    status: "ACTIVE",
    category: "Tech/AI",
    leader: {
      id: "lead_arjun",
      name: "Arjun Rao",
      handle: "arjun_alpha",
      campus: "IIT Bombay",
      winRate: 82,
      maxDrawdown: 5.4,
      skinInGame: 10000,
      totalTrades: 64,
      followers: 1840,
      followersFormatted: "1.8k",
      badge: "Lead Quant",
    },
    lead: {
      id: "lead_arjun",
      name: "Arjun Rao",
      handle: "arjun_alpha",
      campus: "IIT Bombay",
      winRate: 82,
      maxDrawdown: 5.4,
      skinInGame: 10000,
      totalTrades: 64,
      followers: 1840,
      followersFormatted: "1.8k",
      badge: "Lead Quant",
    },
  },
  {
    id: "syn_tsla_robotaxi",
    title: "TSLA Cybercab FSD V13 Regulatory Approval",
    catalyst: "Autonomous ride-hailing commercial testing permit in California + end-to-end neural net release.",
    assetSymbol: "TSLA",
    ticker: "TSLA",
    assetName: "Tesla Inc",
    direction: "LONG",
    leverage: 10,
    entryPrice: 245.20,
    stopLossPrice: 242.75,
    targetPrice: 294.24,
    targetReturnPct: 40,
    returnTarget: 40,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 200000,
    currentPooled: 140000,
    pooledAmount: 140000,
    participants: 980,
    status: "ACTIVE",
    category: "High-Beta",
    leader: {
      id: "lead_kavya",
      name: "Kavya Sharma",
      handle: "kavya_quant",
      campus: "BITS Pilani",
      winRate: 76,
      maxDrawdown: 7.8,
      skinInGame: 7500,
      totalTrades: 52,
      followers: 1420,
      followersFormatted: "1.4k",
      badge: "Momentum Lead",
    },
    lead: {
      id: "lead_kavya",
      name: "Kavya Sharma",
      handle: "kavya_quant",
      campus: "BITS Pilani",
      winRate: 76,
      maxDrawdown: 7.8,
      skinInGame: 7500,
      totalTrades: 52,
      followers: 1420,
      followersFormatted: "1.4k",
      badge: "Momentum Lead",
    },
  },
  {
    id: "syn_aapl_supply",
    title: "AAPL M4 Ultra & Apple Intelligence Upgrade Cycle",
    catalyst: "Foxconn manufacturing ramp + domestic enterprise adoption of localized Apple Intelligence devices.",
    assetSymbol: "AAPL",
    ticker: "AAPL",
    assetName: "Apple Inc",
    direction: "LONG",
    leverage: 8,
    entryPrice: 228.40,
    stopLossPrice: 225.55,
    targetPrice: 251.24,
    targetReturnPct: 24,
    returnTarget: 24,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 150000,
    currentPooled: 98000,
    pooledAmount: 98000,
    participants: 710,
    status: "ACTIVE",
    category: "Consumer Tech",
    leader: {
      id: "lead_rohan",
      name: "Rohan Deshmukh",
      handle: "rohan_trades",
      campus: "RVCE Bengaluru",
      winRate: 79,
      maxDrawdown: 4.2,
      skinInGame: 6000,
      totalTrades: 48,
      followers: 960,
      followersFormatted: "960",
      badge: "Macro Specialist",
    },
    lead: {
      id: "lead_rohan",
      name: "Rohan Deshmukh",
      handle: "rohan_trades",
      campus: "RVCE Bengaluru",
      winRate: 79,
      maxDrawdown: 4.2,
      skinInGame: 6000,
      totalTrades: 48,
      followers: 960,
      followersFormatted: "960",
      badge: "Macro Specialist",
    },
  },
  {
    id: "syn_msft_copilot",
    title: "MSFT Azure Copilot Cloud Acceleration",
    catalyst: "Commercial enterprise Copilot seat growth outperforming guidance; 34% YoY Azure revenue velocity.",
    assetSymbol: "MSFT",
    ticker: "MSFT",
    assetName: "Microsoft Corp",
    direction: "LONG",
    leverage: 10,
    entryPrice: 432.00,
    stopLossPrice: 427.68,
    targetPrice: 480.00,
    targetReturnPct: 28,
    returnTarget: 28,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 300000,
    currentPooled: 240000,
    pooledAmount: 240000,
    participants: 1350,
    status: "ACTIVE",
    category: "Tech/AI",
    leader: {
      id: "lead_ananya",
      name: "Ananya Iyer",
      handle: "ananya_macro",
      campus: "IIT Madras",
      winRate: 84,
      maxDrawdown: 3.8,
      skinInGame: 12000,
      totalTrades: 72,
      followers: 1240,
      followersFormatted: "1.2k",
      badge: "Enterprise Lead",
    },
    lead: {
      id: "lead_ananya",
      name: "Ananya Iyer",
      handle: "ananya_macro",
      campus: "IIT Madras",
      winRate: 84,
      maxDrawdown: 3.8,
      skinInGame: 12000,
      totalTrades: 72,
      followers: 1240,
      followersFormatted: "1.2k",
      badge: "Enterprise Lead",
    },
  },
  {
    id: "syn_amzn_aws",
    title: "AMZN AWS GenAI Infrastructure Rebound",
    catalyst: "Trainium2 silicon deployments slashing model inference costs + retail operating margin beat.",
    assetSymbol: "AMZN",
    ticker: "AMZN",
    assetName: "Amazon.com Inc",
    direction: "LONG",
    leverage: 10,
    entryPrice: 192.50,
    stopLossPrice: 190.57,
    targetPrice: 215.00,
    targetReturnPct: 30,
    returnTarget: 30,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 180000,
    currentPooled: 115000,
    pooledAmount: 115000,
    participants: 690,
    status: "ACTIVE",
    category: "Earnings",
    leader: {
      id: "lead_sid",
      name: "Siddharth Jain",
      handle: "sid_jain_fno",
      campus: "PES University",
      winRate: 75,
      maxDrawdown: 6.9,
      skinInGame: 5000,
      totalTrades: 38,
      followers: 820,
      followersFormatted: "820",
      badge: "Catalyst Trader",
    },
    lead: {
      id: "lead_sid",
      name: "Siddharth Jain",
      handle: "sid_jain_fno",
      campus: "PES University",
      winRate: 75,
      maxDrawdown: 6.9,
      skinInGame: 5000,
      totalTrades: 38,
      followers: 820,
      followersFormatted: "820",
      badge: "Catalyst Trader",
    },
  },
  {
    id: "syn_googl_gemini",
    title: "GOOGL Gemini 2.0 API Monetization Breakout",
    catalyst: "Search generative summaries stabilizing search ad ROAS + Vertex AI consumption spike.",
    assetSymbol: "GOOGL",
    ticker: "GOOGL",
    assetName: "Alphabet Inc",
    direction: "LONG",
    leverage: 8,
    entryPrice: 168.20,
    stopLossPrice: 166.10,
    targetPrice: 189.50,
    targetReturnPct: 26,
    returnTarget: 26,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 200000,
    currentPooled: 155000,
    pooledAmount: 155000,
    participants: 840,
    status: "ACTIVE",
    category: "Tech/AI",
    leader: {
      id: "lead_meera",
      name: "Meera Nair",
      handle: "meera_ai_trader",
      campus: "NIT Surathkal",
      winRate: 80,
      maxDrawdown: 5.1,
      skinInGame: 8000,
      totalTrades: 56,
      followers: 1100,
      followersFormatted: "1.1k",
      badge: "Algo Quant",
    },
    lead: {
      id: "lead_meera",
      name: "Meera Nair",
      handle: "meera_ai_trader",
      campus: "NIT Surathkal",
      winRate: 80,
      maxDrawdown: 5.1,
      skinInGame: 8000,
      totalTrades: 56,
      followers: 1100,
      followersFormatted: "1.1k",
      badge: "Algo Quant",
    },
  },
  {
    id: "syn_meta_llama",
    title: "META Llama 4 Open-Source Compute Advantage",
    catalyst: "Ad auction CPM efficiency surge driven by Advantage+ automated creative AI engines.",
    assetSymbol: "META",
    ticker: "META",
    assetName: "Meta Platforms",
    direction: "LONG",
    leverage: 10,
    entryPrice: 582.00,
    stopLossPrice: 576.18,
    targetPrice: 650.00,
    targetReturnPct: 38,
    returnTarget: 38,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 280000,
    currentPooled: 220000,
    pooledAmount: 220000,
    participants: 1120,
    status: "ACTIVE",
    category: "High-Beta",
    leader: {
      id: "lead_vikram",
      name: "Vikramaditya V.",
      handle: "vikram_quant",
      campus: "IIIT Hyderabad",
      winRate: 83,
      maxDrawdown: 6.2,
      skinInGame: 10000,
      totalTrades: 62,
      followers: 1650,
      followersFormatted: "1.6k",
      badge: "High Beta Lead",
    },
    lead: {
      id: "lead_vikram",
      name: "Vikramaditya V.",
      handle: "vikram_quant",
      campus: "IIIT Hyderabad",
      winRate: 83,
      maxDrawdown: 6.2,
      skinInGame: 10000,
      totalTrades: 62,
      followers: 1650,
      followersFormatted: "1.6k",
      badge: "High Beta Lead",
    },
  },
  {
    id: "syn_amd_mi325x",
    title: "AMD Instinct MI325X Datacenter Challenge",
    catalyst: "Commercial hyperscaler silicon share gain in high-memory inference workloads.",
    assetSymbol: "AMD",
    ticker: "AMD",
    assetName: "Advanced Micro Devices",
    direction: "LONG",
    leverage: 10,
    entryPrice: 156.40,
    stopLossPrice: 154.83,
    targetPrice: 178.00,
    targetReturnPct: 42,
    returnTarget: 42,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 140000,
    currentPooled: 85000,
    pooledAmount: 85000,
    participants: 580,
    status: "ACTIVE",
    category: "Tech/AI",
    leader: {
      id: "lead_devansh",
      name: "Devansh Patel",
      handle: "devansh_fno",
      campus: "Delhi University",
      winRate: 74,
      maxDrawdown: 8.5,
      skinInGame: 4500,
      totalTrades: 42,
      followers: 740,
      followersFormatted: "740",
      badge: "Semi Specialist",
    },
    lead: {
      id: "lead_devansh",
      name: "Devansh Patel",
      handle: "devansh_fno",
      campus: "Delhi University",
      winRate: 74,
      maxDrawdown: 8.5,
      skinInGame: 4500,
      totalTrades: 42,
      followers: 740,
      followersFormatted: "740",
      badge: "Semi Specialist",
    },
  },
  {
    id: "syn_pltr_aip",
    title: "PLTR AIP Defense & Enterprise Contracting Expansion",
    catalyst: "US DoD multi-year defense data fabric allocation + commercial AIP client count doubling.",
    assetSymbol: "PLTR",
    ticker: "PLTR",
    assetName: "Palantir Technologies",
    direction: "LONG",
    leverage: 10,
    entryPrice: 44.10,
    stopLossPrice: 43.65,
    targetPrice: 52.00,
    targetReturnPct: 45,
    returnTarget: 45,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 350000,
    currentPooled: 310000,
    pooledAmount: 310000,
    participants: 1890,
    status: "ACTIVE",
    category: "High-Beta",
    leader: {
      id: "lead_tanvi",
      name: "Tanvi Kulkarni",
      handle: "tanvi_alpha",
      campus: "IIT Bombay",
      winRate: 85,
      maxDrawdown: 5.8,
      skinInGame: 15000,
      totalTrades: 79,
      followers: 2100,
      followersFormatted: "2.1k",
      badge: "Top Alpha Lead",
    },
    lead: {
      id: "lead_tanvi",
      name: "Tanvi Kulkarni",
      handle: "tanvi_alpha",
      campus: "IIT Bombay",
      winRate: 85,
      maxDrawdown: 5.8,
      skinInGame: 15000,
      totalTrades: 79,
      followers: 2100,
      followersFormatted: "2.1k",
      badge: "Top Alpha Lead",
    },
  },
  {
    id: "syn_coin_base",
    title: "COIN Crypto Volume Surge & Base L2 Fee Capture",
    catalyst: "Spot market volumes doubling + non-custodial Base sequencer fees reaching institutional scale.",
    assetSymbol: "COIN",
    ticker: "COIN",
    assetName: "Coinbase Global",
    direction: "LONG",
    leverage: 10,
    entryPrice: 214.50,
    stopLossPrice: 212.35,
    targetPrice: 255.00,
    targetReturnPct: 50,
    returnTarget: 50,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 250000,
    currentPooled: 195000,
    pooledAmount: 195000,
    participants: 1340,
    status: "ACTIVE",
    category: "Crypto",
    leader: {
      id: "lead_aditya",
      name: "Aditya Hegde",
      handle: "aditya_crypto",
      campus: "RVCE Bengaluru",
      winRate: 77,
      maxDrawdown: 9.2,
      skinInGame: 12000,
      totalTrades: 68,
      followers: 1920,
      followersFormatted: "1.9k",
      badge: "Web3 Strategist",
    },
    lead: {
      id: "lead_aditya",
      name: "Aditya Hegde",
      handle: "aditya_crypto",
      campus: "RVCE Bengaluru",
      winRate: 77,
      maxDrawdown: 9.2,
      skinInGame: 12000,
      totalTrades: 68,
      followers: 1920,
      followersFormatted: "1.9k",
      badge: "Web3 Strategist",
    },
  },
  {
    id: "syn_btc_perp",
    title: "BTC Institutional Inflow & Macro Liquidity Breakout",
    catalyst: "Global sovereign reserve accumulation proposals and record weekly ETF net creation units.",
    assetSymbol: "BTC",
    ticker: "BTC",
    assetName: "Bitcoin Perpetual",
    direction: "LONG",
    leverage: 10,
    entryPrice: 67800.00,
    stopLossPrice: 67122.00,
    targetPrice: 76000.00,
    targetReturnPct: 35,
    returnTarget: 35,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 500000,
    currentPooled: 430000,
    pooledAmount: 430000,
    participants: 2850,
    status: "ACTIVE",
    category: "Crypto",
    leader: {
      id: "lead_pranav",
      name: "Pranav Menon",
      handle: "pranav_macro",
      campus: "BITS Pilani",
      winRate: 81,
      maxDrawdown: 6.0,
      skinInGame: 25000,
      totalTrades: 94,
      followers: 3200,
      followersFormatted: "3.2k",
      badge: "Macro Veteran",
    },
    lead: {
      id: "lead_pranav",
      name: "Pranav Menon",
      handle: "pranav_macro",
      campus: "BITS Pilani",
      winRate: 81,
      maxDrawdown: 6.0,
      skinInGame: 25000,
      totalTrades: 94,
      followers: 3200,
      followersFormatted: "3.2k",
      badge: "Macro Veteran",
    },
  },
  {
    id: "syn_eth_staking",
    title: "ETH Layer-1 Staking Supply Squeeze",
    catalyst: "Liquid staking ratios reducing liquid exchange supply alongside gas burn acceleration.",
    assetSymbol: "ETH",
    ticker: "ETH",
    assetName: "Ethereum Perpetual",
    direction: "LONG",
    leverage: 10,
    entryPrice: 2640.00,
    stopLossPrice: 2613.60,
    targetPrice: 3050.00,
    targetReturnPct: 38,
    returnTarget: 38,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 220000,
    currentPooled: 165000,
    pooledAmount: 165000,
    participants: 940,
    status: "ACTIVE",
    category: "Crypto",
    leader: {
      id: "lead_sneha",
      name: "Sneha Reddy",
      handle: "sneha_eth",
      campus: "IIT Madras",
      winRate: 78,
      maxDrawdown: 7.4,
      skinInGame: 9000,
      totalTrades: 58,
      followers: 1520,
      followersFormatted: "1.5k",
      badge: "DeFi Lead",
    },
    lead: {
      id: "lead_sneha",
      name: "Sneha Reddy",
      handle: "sneha_eth",
      campus: "IIT Madras",
      winRate: 78,
      maxDrawdown: 7.4,
      skinInGame: 9000,
      totalTrades: 58,
      followers: 1520,
      followersFormatted: "1.5k",
      badge: "DeFi Lead",
    },
  },
  {
    id: "syn_arm_edge",
    title: "ARM Architecture v9 Edge Mobile Penetration",
    catalyst: "Royalty rate doubling on AI-capable edge smartphones and PC processor licensings.",
    assetSymbol: "ARM",
    ticker: "ARM",
    assetName: "ARM Holdings",
    direction: "LONG",
    leverage: 8,
    entryPrice: 142.10,
    stopLossPrice: 140.32,
    targetPrice: 164.00,
    targetReturnPct: 28,
    returnTarget: 28,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 120000,
    currentPooled: 74000,
    pooledAmount: 74000,
    participants: 490,
    status: "ACTIVE",
    category: "Tech/AI",
    leader: {
      id: "lead_karthik",
      name: "Karthik Swaminathan",
      handle: "karthik_chips",
      campus: "PES University",
      winRate: 73,
      maxDrawdown: 7.1,
      skinInGame: 4000,
      totalTrades: 35,
      followers: 680,
      followersFormatted: "680",
      badge: "Edge AI Lead",
    },
    lead: {
      id: "lead_karthik",
      name: "Karthik Swaminathan",
      handle: "karthik_chips",
      campus: "PES University",
      winRate: 73,
      maxDrawdown: 7.1,
      skinInGame: 4000,
      totalTrades: 35,
      followers: 680,
      followersFormatted: "680",
      badge: "Edge AI Lead",
    },
  },
  {
    id: "syn_nflx_ads",
    title: "NFLX Ad-Tier Subscriber Beat & Live Sports Ramp",
    catalyst: "High-margin ad revenue doubling; holiday season NFL live broadcast lock-in.",
    assetSymbol: "NFLX",
    ticker: "NFLX",
    assetName: "Netflix Inc",
    direction: "LONG",
    leverage: 8,
    entryPrice: 712.00,
    stopLossPrice: 703.10,
    targetPrice: 780.00,
    targetReturnPct: 22,
    returnTarget: 22,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 160000,
    currentPooled: 112000,
    pooledAmount: 112000,
    participants: 780,
    status: "ACTIVE",
    category: "Consumer Tech",
    leader: {
      id: "lead_pooja",
      name: "Pooja Bansal",
      handle: "pooja_equity",
      campus: "Delhi University",
      winRate: 79,
      maxDrawdown: 4.6,
      skinInGame: 6500,
      totalTrades: 46,
      followers: 890,
      followersFormatted: "890",
      badge: "Earnings Specialist",
    },
    lead: {
      id: "lead_pooja",
      name: "Pooja Bansal",
      handle: "pooja_equity",
      campus: "Delhi University",
      winRate: 79,
      maxDrawdown: 4.6,
      skinInGame: 6500,
      totalTrades: 46,
      followers: 890,
      followersFormatted: "890",
      badge: "Earnings Specialist",
    },
  },
  {
    id: "syn_uber_robot",
    title: "UBER Autonomous Fleet Delivery Partnership",
    catalyst: "Platform delivery tie-ins with Waymo and Avride expanding autonomous ride trips by 3x.",
    assetSymbol: "UBER",
    ticker: "UBER",
    assetName: "Uber Technologies",
    direction: "LONG",
    leverage: 8,
    entryPrice: 78.90,
    stopLossPrice: 77.91,
    targetPrice: 89.50,
    targetReturnPct: 25,
    returnTarget: 25,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 130000,
    currentPooled: 88000,
    pooledAmount: 88000,
    participants: 610,
    status: "ACTIVE",
    category: "Earnings",
    leader: {
      id: "lead_harsh",
      name: "Harsh Vardhan",
      handle: "harsh_catalyst",
      campus: "NIT Surathkal",
      winRate: 76,
      maxDrawdown: 5.9,
      skinInGame: 5500,
      totalTrades: 40,
      followers: 710,
      followersFormatted: "710",
      badge: "Platform Quant",
    },
    lead: {
      id: "lead_harsh",
      name: "Harsh Vardhan",
      handle: "harsh_catalyst",
      campus: "NIT Surathkal",
      winRate: 76,
      maxDrawdown: 5.9,
      skinInGame: 5500,
      totalTrades: 40,
      followers: 710,
      followersFormatted: "710",
      badge: "Platform Quant",
    },
  },
  {
    id: "syn_intc_foundry",
    title: "INTC 18A Foundry Commercial Breakthrough",
    catalyst: "External commercial packaging and 18A fab tape-outs demonstrating power-performance parity.",
    assetSymbol: "INTC",
    ticker: "INTC",
    assetName: "Intel Corp",
    direction: "LONG",
    leverage: 10,
    entryPrice: 22.60,
    stopLossPrice: 22.37,
    targetPrice: 28.00,
    targetReturnPct: 48,
    returnTarget: 48,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 150000,
    currentPooled: 92000,
    pooledAmount: 92000,
    participants: 740,
    status: "ACTIVE",
    category: "High-Beta",
    leader: {
      id: "lead_gaurav",
      name: "Gaurav Sen",
      handle: "gaurav_deepvalue",
      campus: "IIIT Hyderabad",
      winRate: 72,
      maxDrawdown: 8.9,
      skinInGame: 5000,
      totalTrades: 51,
      followers: 1050,
      followersFormatted: "1.0k",
      badge: "Deep Value Lead",
    },
    lead: {
      id: "lead_gaurav",
      name: "Gaurav Sen",
      handle: "gaurav_deepvalue",
      campus: "IIIT Hyderabad",
      winRate: 72,
      maxDrawdown: 8.9,
      skinInGame: 5000,
      totalTrades: 51,
      followers: 1050,
      followersFormatted: "1.0k",
      badge: "Deep Value Lead",
    },
  },
  {
    id: "syn_tsm_nanometer",
    title: "TSM 2nm Sub-Nanometer Yield Rate Superiority",
    catalyst: "Foundry gross margins expanding towards 56% on undisputed global 3nm/2nm pricing power.",
    assetSymbol: "TSM",
    ticker: "TSM",
    assetName: "Taiwan Semiconductor",
    direction: "LONG",
    leverage: 10,
    entryPrice: 194.20,
    stopLossPrice: 192.25,
    targetPrice: 225.00,
    targetReturnPct: 32,
    returnTarget: 32,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 320000,
    currentPooled: 275000,
    pooledAmount: 275000,
    participants: 1680,
    status: "ACTIVE",
    category: "Tech/AI",
    leader: {
      id: "lead_akash",
      name: "Akash Singhal",
      handle: "akash_semi",
      campus: "IIT Bombay",
      winRate: 86,
      maxDrawdown: 3.9,
      skinInGame: 14000,
      totalTrades: 85,
      followers: 1750,
      followersFormatted: "1.7k",
      badge: "Master Quant",
    },
    lead: {
      id: "lead_akash",
      name: "Akash Singhal",
      handle: "akash_semi",
      campus: "IIT Bombay",
      winRate: 86,
      maxDrawdown: 3.9,
      skinInGame: 14000,
      totalTrades: 85,
      followers: 1750,
      followersFormatted: "1.7k",
      badge: "Master Quant",
    },
  },
  {
    id: "syn_baba_stimulus",
    title: "BABA Cloud AI & Consumer Liquidity Stimulus",
    catalyst: "Macro liquidity stimulus package in China + Cloud AI monetization reversing margin drag.",
    assetSymbol: "BABA",
    ticker: "BABA",
    assetName: "Alibaba Group",
    direction: "LONG",
    leverage: 8,
    entryPrice: 102.30,
    stopLossPrice: 101.02,
    targetPrice: 122.00,
    targetReturnPct: 36,
    returnTarget: 36,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 160000,
    currentPooled: 105000,
    pooledAmount: 105000,
    participants: 670,
    status: "ACTIVE",
    category: "High-Beta",
    leader: {
      id: "lead_nikhil",
      name: "Nikhil Joshi",
      handle: "nikhil_global",
      campus: "BITS Pilani",
      winRate: 75,
      maxDrawdown: 9.8,
      skinInGame: 6000,
      totalTrades: 45,
      followers: 940,
      followersFormatted: "940",
      badge: "Global Macro Lead",
    },
    lead: {
      id: "lead_nikhil",
      name: "Nikhil Joshi",
      handle: "nikhil_global",
      campus: "BITS Pilani",
      winRate: 75,
      maxDrawdown: 9.8,
      skinInGame: 6000,
      totalTrades: 45,
      followers: 940,
      followersFormatted: "940",
      badge: "Global Macro Lead",
    },
  },
  {
    id: "syn_dis_streaming",
    title: "DIS Direct-to-Consumer Streaming Profitability",
    catalyst: "Parks capacity normalization + streaming operating income turning permanently positive.",
    assetSymbol: "DIS",
    ticker: "DIS",
    assetName: "Walt Disney Co",
    direction: "LONG",
    leverage: 5,
    entryPrice: 96.80,
    stopLossPrice: 94.86,
    targetPrice: 108.00,
    targetReturnPct: 20,
    returnTarget: 20,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 100000,
    currentPooled: 64000,
    pooledAmount: 64000,
    participants: 410,
    status: "ACTIVE",
    category: "Consumer Tech",
    leader: {
      id: "lead_shreya",
      name: "Shreya Verma",
      handle: "shreya_val",
      campus: "Delhi University",
      winRate: 74,
      maxDrawdown: 5.2,
      skinInGame: 4000,
      totalTrades: 32,
      followers: 620,
      followersFormatted: "620",
      badge: "Value Strategist",
    },
    lead: {
      id: "lead_shreya",
      name: "Shreya Verma",
      handle: "shreya_val",
      campus: "Delhi University",
      winRate: 74,
      maxDrawdown: 5.2,
      skinInGame: 4000,
      totalTrades: 32,
      followers: 620,
      followersFormatted: "620",
      badge: "Value Strategist",
    },
  },
  {
    id: "syn_avgo_asic",
    title: "AVGO Custom AI ASIC Acceleration & VMware Synergy",
    catalyst: "Hyperscaler custom TPU / XPU networking silicon demand surging above expectations.",
    assetSymbol: "AVGO",
    ticker: "AVGO",
    assetName: "Broadcom Inc",
    direction: "LONG",
    leverage: 10,
    entryPrice: 178.60,
    stopLossPrice: 176.81,
    targetPrice: 206.00,
    targetReturnPct: 32,
    returnTarget: 32,
    circuitBreakerPct: -10,
    stopLoss: -10,
    minPledge: 50,
    poolCap: 260000,
    currentPooled: 210000,
    pooledAmount: 210000,
    participants: 1290,
    status: "ACTIVE",
    category: "Tech/AI",
    leader: {
      id: "lead_madhav",
      name: "Madhav Tandon",
      handle: "madhav_alpha",
      campus: "RVCE Bengaluru",
      winRate: 82,
      maxDrawdown: 4.8,
      skinInGame: 11000,
      totalTrades: 60,
      followers: 1310,
      followersFormatted: "1.3k",
      badge: "Silicon Quant",
    },
    lead: {
      id: "lead_madhav",
      name: "Madhav Tandon",
      handle: "madhav_alpha",
      campus: "RVCE Bengaluru",
      winRate: 82,
      maxDrawdown: 4.8,
      skinInGame: 11000,
      totalTrades: 60,
      followers: 1310,
      followersFormatted: "1.3k",
      badge: "Silicon Quant",
    },
  },
];

export const DEFAULT_MOCK_USER = {
  id: "user_demo",
  name: "Priyanka S.",
  handle: "priyanka_s",
  campus: "RVCE Bengaluru - Hostel Block 1",
  upiId: "priyanka@okhdfcbank",
  balance: 1500.00,
  walletBalance: 1500.00,
};

export const DEFAULT_MOCK_ACTIVE_POSITION = {
  id: "pos_nvda_active",
  syndicateId: "syn_nvda_q3",
  status: "ACTIVE",
  currentPrice: 130.86,
  unrealizedPnlPct: 18.4,
  pledgeAmount: 100.0,
  notionalAmount: 1000.0,
  syndicate: DEFAULT_MOCK_SYNDICATES[0],
  pnl: {
    unrealizedPnlInr: 18.40,
    positionReturnPct: 18.40,
    currentValueInr: 118.40,
    isStopLossTriggered: false,
    isTargetHit: false,
  },
  latestPledge: {
    id: "pld_demo_active",
    amount: 100.0,
    upiUtr: "UPI/984712/AXIS",
    escrowStatus: "LOCKED",
    createdAt: new Date().toISOString(),
  },
};

export const DEFAULT_MOCK_SETTLEMENT = {
  id: "stl_tsla_cb",
  positionId: "pos_tsla_settled",
  userId: "user_demo",
  initialPledge: 100.0,
  grossPayout: 90.0,
  leaderFee: 0.0,
  protocolFee: 0.0,
  netPayout: 90.0,
  upiRefundUtr: "UPI/MOCHA/789102/SHIELD",
  settlementTimeSec: 3.8,
  createdAt: new Date("2026-09-25T14:30:00Z").toISOString(),
  position: {
    id: "pos_tsla_settled",
    syndicateId: "syn_tsla_robotaxi",
    status: "SETTLED",
    exitReason: "CIRCUIT_BREAKER",
    entryPrice: 245.20,
    exitPrice: 242.75,
    currentPrice: 242.75,
    unrealizedPnlPct: -10.0,
    syndicate: DEFAULT_MOCK_SYNDICATES[1],
  },
};

export const DEFAULT_MOCK_PORTFOLIO = {
  user: DEFAULT_MOCK_USER,
  activePledges: [
    {
      id: "pos_nvda_active",
      syndicateId: "syn_nvda_q3",
      pledgeAmount: 100.0,
      notionalAmount: 1000.0,
      entryPrice: 128.50,
      currentPrice: 130.86,
      pnl: 18.40,
      pnlPct: 18.40,
      leverage: 10,
      status: "ACTIVE",
      title: "NVDA Q3 Blackwell Data Center Surge",
      syndicate: DEFAULT_MOCK_SYNDICATES[0],
    },
  ],
  settlements: [DEFAULT_MOCK_SETTLEMENT],
  metrics: {
    totalPledged: 200.00,
    totalPayout: 208.40,
    netPnl: 8.40,
    capitalSaved: 90.00,
    tradesCount: 2,
  },
};

export function getFallbackSyndicate(id: string): SyndicateItem {
  const found = DEFAULT_MOCK_SYNDICATES.find((s) => s.id === id);
  if (found) return found;
  return DEFAULT_MOCK_SYNDICATES[0];
}

export function getFallbackPosition(id: string) {
  const matched = DEFAULT_MOCK_SYNDICATES.find(
    (s) => s.id === id || s.assetSymbol.toLowerCase() === id.toLowerCase()
  );
  if (matched) {
    return {
      ...DEFAULT_MOCK_ACTIVE_POSITION,
      id: `pos_${matched.assetSymbol.toLowerCase()}_active`,
      syndicateId: matched.id,
      syndicate: matched,
    };
  }
  return DEFAULT_MOCK_ACTIVE_POSITION;
}

export function getFallbackSettlement(id: string) {
  return DEFAULT_MOCK_SETTLEMENT;
}
